---
version: "3"

services:
    flask-app:
        platform: linux/arm64
        build:
            context: ./
            dockerfile: ./Dockerfile
        image: ashtonvcole/hurricane-damage-api
        ports:
            - 5000:5000
